### PR TITLE
Added the functionality to convert any arbitrary Topojson

### PR DESCRIPTION
**Pull request by devdattaT**
In this commit, I've Added the functionality to convert any arbitrary TopoJSON, with any arbitrary collection name, as well as multiple collections in one TopoJSON. I think this should solve the existing issue that you have logged.

### CODE REVIEW

**Comment by JeffPaine** [comment]
Thanks so much for this PR! I'll have some time tonight to review it. Sorry for the delay :smile:

**Comment by JeffPaine** [comment]
So I like where you're going with this. I'd like to minimize the number of files in the project. To that end, what do you think about taking the contents of `GeoJSON.js` and adding them to `index.html`?

**Comment by devdattaT** [comment]
I have no problems integrating that code within a script tag on the
index.html
I had kept it separate to make it easy to see the changes in the pull
request.

Do you want me to make this change in my repo so that you get it in the
pull request?

**Comment by JeffPaine** [comment]
Ahh, I understand. Thank you.

Yes, if you don't mind combining it into index.html, that would be great.
Thanks so much!!

## 

Jeff

**Comment by devdattaT** [comment]
I've updated my repo with two commits:
1. Moved GeoJSON code to the `Index.html`
2. Solved some bugs when multiple collections are present in the Topojson

**Comment by JeffPaine** [comment]
Great work, thanks very much for your time!

**Pull request merged**
